### PR TITLE
Make the import account and export account methods not async

### PR DESCRIPTION
**Pull request by ghost**
Reason: LL de/serialization isn't async.

### CODE REVIEW

**Comment by machard** [comment]
It's async though, because storage are not necessary in memory :/
I think its manageable on llc side even with async

**Comment by haammar-ledger** [comment]
> It's async though, because storage are not necessary in memory :/
> I think its manageable on llc side even with async

Good point, but we'll never use a physical storage in a LL scenario since that would be duplicate. Can we consider providing 2 methods, one sync and one async maybe?
Otherwise I'm not sure how to call async import and export from LL sync storage, do you have an idea?

**Comment by haammar-ledger** [comment]
Btw I'm having the same issue when replacing LL's utxos with calls to `wallet.getAccountUnspentUtxos`.
There are places where this call can't be async.

**Comment by machard** [comment]
well indeed the fact that serialization does not handle async serializers in llc is not fixable in a straightforward way...

**Comment by machard** [comment]
https://github.com/LedgerHQ/wallet-btc/pull/26

**Pull request closed without merging**
