### PR TITLE
LL-6293

### PR DESCRIPTION
**Pull request by hzheng-ledger**
Support all the btc family(sync) and add tests
https://ledgerhq.atlassian.net/browse/LL-6293

### CODE REVIEW

**Comment by machard** [comment]
build/sign/send transactions work out of the box on these coins ?

**Comment by hzheng-ledger** [comment]
> build/sign/send transactions work out of the box on these coins ?

not yet, I'll have a try next week

**Comment by machard** [comment]
from slack:
i would suggest to keep just one explorer class and just add the optional param when you initialize, like disableBatchSize

**Comment by hzheng-ledger** [comment]
> from slack:
> i would suggest to keep just one explorer class and just add the optional param when you initialize, like disableBatchSize

Fixed

**Pull request merged**
